<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-05T10:34:12Z" name="Default suite" finished-at="2021-01-05T10:34:41Z" duration-ms="28810">
    <groups>
    </groups>
    <test started-at="2021-01-05T10:34:12Z" name="Default test" finished-at="2021-01-05T10:34:41Z" duration-ms="28810">
      <class name="com.sample.tests.FeaturesNeg">
        <test-method is-config="true" signature="init()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:12Z" name="init" finished-at="2021-01-05T10:34:20Z" duration-ms="7835" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:20Z" name="setUp" finished-at="2021-01-05T10:34:20Z" duration-ms="25" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Title()[pri:1, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:20Z" name="Title" finished-at="2021-01-05T10:34:20Z" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Pizza Order] but found [Pizza Order Form]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Pizza Order] but found [Pizza Order Form]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.sample.tests.FeaturesNeg.Title(FeaturesNeg.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Title -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:20Z" name="setUp" finished-at="2021-01-05T10:34:20Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="PizzaMenu()[pri:2, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:20Z" name="PizzaMenu" finished-at="2021-01-05T10:34:23Z" duration-ms="3186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PizzaMenu -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:23Z" name="setUp" finished-at="2021-01-05T10:34:23Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="ToppingsMenu1()[pri:3, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:23Z" name="ToppingsMenu1" finished-at="2021-01-05T10:34:25Z" duration-ms="2143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ToppingsMenu1 -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:25Z" name="setUp" finished-at="2021-01-05T10:34:25Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="ToppingsMenu2()[pri:4, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:25Z" name="ToppingsMenu2" finished-at="2021-01-05T10:34:28Z" duration-ms="2229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ToppingsMenu2 -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:28Z" name="setUp" finished-at="2021-01-05T10:34:28Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="PaymentInfo()[pri:5, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:28Z" name="PaymentInfo" finished-at="2021-01-05T10:34:31Z" duration-ms="3057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PaymentInfo -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:31Z" name="setUp" finished-at="2021-01-05T10:34:31Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="OrderWithMissingInfo()[pri:6, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:31Z" name="OrderWithMissingInfo" description="Verifying dialog box should appear for missing fields " finished-at="2021-01-05T10:34:41Z" duration-ms="10183" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[modal dialog appeared with error message expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: modal dialog appeared with error message expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.sample.test.demo.TestBase.markFail(TestBase.java:103)
at com.sample.tests.FeaturesNeg.OrderWithMissingInfo(FeaturesNeg.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderWithMissingInfo -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.sample.tests.FeaturesNeg@7dc19a70]" started-at="2021-01-05T10:34:41Z" name="tearDown" finished-at="2021-01-05T10:34:41Z" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sample.tests.FeaturesNeg -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
